CREATE SCHEMA IF NOT EXISTS ext_source;
CREATE SCHEMA IF NOT EXISTS src;
CREATE SCHEMA IF NOT EXISTS stg_cln;
CREATE SCHEMA IF NOT EXISTS bl_3nf;
CREATE SCHEMA IF NOT EXISTS bl_dm;
CREATE SCHEMA IF NOT EXISTS bl_cn;